filter:
    excluded_paths:
        - tests/*
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_analyzer: true
    php_mess_detector: true
    external_code_coverage: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_pdepend: true
    sensiolabs_security_checker: true

build:
    tests:
        override:
            -
                command: vendor/bin/phpunit  --coverage-clover=my-coverage-file --configuration=phpunit.xml.dist
                coverage:
                    file: my-coverage-file
                    format: php-clover
